# -*- coding: utf-8 -*-
"""Day71.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4FzJef46eB24K2YIxYKdGgjWvbCjLRW
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/salaries_by_college_major (1).csv')
df.head()
len(df)

len(df)

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()
print(clean_df)

clean_df.tail()

highest_major_index = clean_df['Starting Median Salary'].idxmax()
print(clean_df['Undergraduate Major'].loc[highest_major_index])

highest_mid_careeridx = clean_df['Mid-Career Median Salary'].idxmax()
print(clean_df['Undergraduate Major'][highest_mid_careeridx])
print(clean_df['Mid-Career Median Salary'].max())

lowest_idx = clean_df['Starting Median Salary'].idxmin()
lowest_idx_career = clean_df['Undergraduate Major'][lowest_idx]
print(lowest_idx_career)
mid_sal = clean_df['Starting Median Salary'][lowest_idx]
print(mid_sal)

print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

diff_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])
clean_df.insert(1, 'Difference', diff_col)

clean_df

low_risk = clean_df.sort_values('Difference')

highest_90th = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_90th[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

high_risk = clean_df.sort_values('Difference', ascending=False)
high_risk[['Undergraduate Major', 'Difference']].head()

pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean()

url = 'https://www.payscale.com/college-salary-report/majors-that-pay-you-back/bachelors'
df_list = pd.read_html(url)
df_list[0]

payscale_df = df_list[0].copy()

payscale_df.columns=['Rank', 'Major', 'Degree Type','Early Career Pay', 'Mid-Career Pay', 'High Meaning']

payscale_df

for page_no in range(2, 3):
  url = f'https://www.payscale.com/college-salary-report/majors-that-pay-you-back/bachelors/page/{page_no}'
  table_from_html = pd.read_html(url)
  temp_table = table_from_html[0].copy()
  temp_table.columns=['Rank', 'Major', 'Degree Type','Early Career Pay', 'Mid-Career Pay', 'High Meaning']
  payscale_df = payscale_df.append(temp_table, ignore_index=True)
payscale_df

payscale_df.replace({'^Major:':"", '^Early Career Pay:\$':"", '^Mid-Career Pay:\$':""}, regex=True, inplace=True)

payscale_df.

payscale_df = payscale_df[['Major', 'Early Career Pay', 'Mid-Career Pay']]

payscale_df